# Generated by Django 4.1.6 on 2023-03-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("publish_date", models.DateField()),
                ("category", models.CharField(max_length=50)),
                ("editor", models.CharField(max_length=50)),
            ],
        ),
    ]
